IFileOpenPickerContinuable interface is not working on universal platform
Without this change I get :
error CS0246: The type or namespace name 'IFileOpenPickerContinuable'
could not be found (are you missing a using directive or an assembly
reference?)